"""create_vehicles_table

Revision ID: 0790fd97b5f7
Revises: 249ec9f25755
Create Date: 2026-03-23 11:36:17.829230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0790fd97b5f7'
down_revision: Union[str, Sequence[str], None] = '249ec9f25755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('branch_tag', sa.String(), nullable=False),
    sa.Column('thumbnail_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('fuel_level_pct', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(), nullable=False),
    sa.Column('security_deposit', sa.Numeric(), nullable=False),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=False),
    sa.Column('rc_expiry_date', sa.Date(), nullable=False),
    sa.Column('puc_expiry_date', sa.Date(), nullable=False),
    sa.Column('insurance_url', sa.String(), nullable=False),
    sa.Column('rc_url', sa.String(), nullable=False),
    sa.Column('puc_url', sa.String(), nullable=False),
    sa.Column('vehicle_status', sa.String(), server_default=sa.text("'available'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fuel_level_pct >= 0 AND fuel_level_pct <= 100', name='fuel_level_range'),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
