"""final_initial

Revision ID: 101d0e5ef8f8
Revises: 
Create Date: 2026-03-31 07:34:26.898925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '101d0e5ef8f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='Customer', nullable=False),
    sa.Column('license_url', sa.String(), nullable=True),
    sa.Column('selfie_url', sa.String(), nullable=True),
    sa.Column('extracted_address', sa.Text(), nullable=True),
    sa.Column('dl_expiry_date', sa.Date(), nullable=True),
    sa.Column('kyc_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
    sa.Column('kyc_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_reviewed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('branch_tag', sa.String(), nullable=False),
    sa.Column('thumbnail_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('fuel_level_pct', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(), nullable=False),
    sa.Column('security_deposit', sa.Numeric(), nullable=False),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('rc_expiry_date', sa.Date(), nullable=True),
    sa.Column('puc_expiry_date', sa.Date(), nullable=True),
    sa.Column('insurance_url', sa.String(), nullable=False),
    sa.Column('rc_url', sa.String(), nullable=False),
    sa.Column('puc_url', sa.String(), nullable=False),
    sa.Column('vehicle_status', sa.String(), server_default=sa.text("'available'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fuel_level_pct >= 0 AND fuel_level_pct <= 100', name='fuel_level_range'),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('rental_fee', sa.Numeric(), nullable=False),
    sa.Column('security_deposit', sa.Numeric(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('is_physically_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('status', sa.String(), server_default='reserved', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('damage_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('pre_rental_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('post_rental_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fuel_level_at_pickup', sa.Integer(), nullable=True),
    sa.Column('fuel_level_at_return', sa.Integer(), nullable=True),
    sa.Column('llm_classification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('fuel_level_at_pickup >= 0 AND fuel_level_at_pickup <= 100', name='check_fuel_pickup_range'),
    sa.CheckConstraint('fuel_level_at_return >= 0 AND fuel_level_at_return <= 100', name='check_fuel_return_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('mock_transaction_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('damage_logs')
    op.drop_table('sessions')
    op.drop_table('bookings')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('async_jobs')
    # ### end Alembic commands ###
