"""create_bookings_payments_damagelogs_tables

Revision ID: ecae7ff4eede
Revises: 
Create Date: 2026-03-23 14:20:52.396564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecae7ff4eede'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('rental_fee', sa.Numeric(), nullable=False),
    sa.Column('security_deposit', sa.Numeric(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('is_physically_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('status', sa.String(), server_default='reserved', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('damage_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('pre_rental_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('post_rental_image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fuel_level_at_pickup', sa.Integer(), nullable=True),
    sa.Column('fuel_level_at_return', sa.Integer(), nullable=True),
    sa.Column('llm_classification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('fuel_level_at_pickup >= 0 AND fuel_level_at_pickup <= 100', name='check_fuel_pickup_range'),
    sa.CheckConstraint('fuel_level_at_return >= 0 AND fuel_level_at_return <= 100', name='check_fuel_return_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('mock_transaction_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('damage_logs')
    op.drop_table('bookings')
    # ### end Alembic commands ###
